name: CMake

on:
  push:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PKG_CONFIG_PATH: ${{github.workspace}}/CLRX/lib/pkgconfig

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Git clone CLRX
        run: git clone https://github.com/CLRX/CLRX-mirror

      - name: Configure CLRX
        run: cmake -H${{github.workspace}}/CLRX-mirror -B ${{github.workspace}}/CLRX-mirror/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=CLRX -DLIB_INSTALL_DIR=lib

      - name: Build CLRX
        run: cmake --build ${{github.workspace}}/CLRX-mirror/build/ --config Release

      - name: Install CLRX
        run: cmake --install ${{github.workspace}}/CLRX-mirror/build/ --config Release --prefix ${{github.workspace}}/CLRX

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
